events {}

http {
    upstream identity_system {
        server 127.0.0.1:9001 max_fails=3 fail_timeout=10s;
    }

    upstream catalog_system {
        server 127.0.0.1:9002 max_fails=3 fail_timeout=10s;
    }

    upstream finance_system {
        server 127.0.0.1:9003 max_fails=3 fail_timeout=10s;
    }

    upstream observability_system {
        server 127.0.0.1:9004 max_fails=3 fail_timeout=10s;
    }

    server {
        listen 8080;
        server_name localhost;

        location /users {
            proxy_pass http://identity_system;
        }

        location /products {
            proxy_pass http://catalog_system;
        }

        location /inventory {
            proxy_pass http://finance_system;
        }

        location /orders {
            proxy_pass http://finance_system;
        }

        location /payments {
            proxy_pass http://finance_system;
        }

        location /invoices {
            proxy_pass http://finance_system;
        }

        location /jobs {
            proxy_pass http://finance_system;
        }

        location /reports {
            proxy_pass http://finance_system;
        }

        location /ops {
            proxy_pass http://observability_system;
        }

        location / {
            return 200 "E-Commerce distributed gateway\n";
        }
    }
}
